import turtle
turtle. showturtle()
turtle. fillcolor('blue')
turtle. begin_fill()
turtle. goto(40,80)
turtle. goto(80,0)
turtle. goto(40,40)
turtle. goto(0,0)
turtle. end_fill()
turtle. goto(80,0)
turtle. exitonclick()
turtle. done